# Generated by Django 4.2.4 on 2024-12-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0002_auto_20240319_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.store', to_field='name'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.store', to_field='name'),
        ),
    ]
