version: "3.9"

services:
  django_gunicorn:
  #     restart: always
    build:
      context: .
      dockerfile: ./Buchungssystem_Lastenkarle/Dockerfile_Django
    volumes:
      - ./Buchungssystem_Lastenkarle/:/usr/src/app/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - envvarsdjango.env
    depends_on:
      db:
        condition: service_healthy


  nginx:
    build: ./nginx
    volumes:
      - ./Buchungssystem_Lastenkarle/static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  db:
    container_name: pg_container
    image: postgres:15.3-bullseye
    restart: always
    environment:
      POSTGRES_USER: Caro
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - ./dev_postgres:/var/lib/postgresql/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "Caro", "-d", "test_db" ]
      interval: 10s
      timeout: 5s
      retries: 3


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: Caro@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "40000:5050"
      - "40001:80"
    expose:
      - "40000"