# Generated by Django 4.2.2 on 2023-06-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Availability_Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.bike')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mail_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(choices=[('KA', 'Karlsruhe'), ('ETT', 'Ettlingen'), ('BAD', 'Baden-Baden'), ('BRU', 'Bruchsal'), ('MAL', 'Malsch')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
                ('assurance_lvl', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('contact_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user_flag')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='OIDC_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='Local_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='ID_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.TextField(max_length=3)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_store_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.store')),
                ('to_user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.booking')),
                ('flag_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.booking_flag')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user'),
        ),
        migrations.AddField(
            model_name='bike',
            name='store_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.store'),
        ),
        migrations.CreateModel(
            name='Availability_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.availability')),
                ('flag_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.availability_flag')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='bike_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.bike'),
        ),
        migrations.AddField(
            model_name='availability',
            name='store_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.store'),
        ),
    ]
